README.md, config-template.py, pkg/database/manager.py, pkg/openai/manager.py, pkg/openai/modelmgr.py, pkg/openai/session.py, pkg/qqbot/command.py, requirements.txt, tests/compatibility_tests/models_and_interfaces.py
主要修改了请求OpenAI官方API的结构，具体做了以下修改：
1、更新openai到0.27.0
2、在pkg.openai.modelmgr模块添加了Model对象
3、用pkg.openai.modelmgr.Model构建了ChatCompletionModel和CompletionModel用来同时支持文本完成API和对话API
4、更新session的prompt为结构，更好的支持不同API，并在pkg.qqbot.command、pkg.database内做了相应调整
可能存在的问题：
1、由于更新了session，相关插件可能要重新适配，但鉴于官方已经开启ChatAPI，且该提交已经适配了ChatAPI，固[revLibs](https://github.com/RockChinQ/revLibs)可以停用，不会影响过大
2、测试中发现有断连警告，但不影响使用，以后再解决
=> 重构了模型抽象，用来更好的支持gpt-3.5-turbo

main.py
主要改动如下：
1、在ensure_dependencies函数更更新包时，出现超时的情况，指定更新源 https://pypi.douban.com/simple/
=> 启动时，更新openai和pillow库超时问题

.gitignore, main.py
支持在config.py同目录建立`override.json`以使用json格式覆写config.py的配置项内容，例如:
```JSON
{
"admin_qq": 12345678
}
```
这样程序将忽略config.py中设置的`admin_qq`值，转而使用此文件中指定的`12345678`为`admin_qq`的值，所有字段均支持，可以查看`config-template.py`  
同样的，数组和字典也受支持，但要注意以json的语法编写，`true`及`false`也请使用json的格式
=> feat: 支持json格式的配置文件 (#265)

pkg/qqbot/command.py, pkg/utils/credit.py
BUG描述：当配置代理时，!usage命令无法读取到代理参数，导致直连请求，最后超时
修复内容：在**pkg/qqbot/command.py**内，调用**pkg/utils/credit.py**的**fetch_credit_data**时，将config内的代理参数传入，并携带代理参数进行请求，要注意proxies参数默认为proxies=None，而不是proxies={None}
=> 修复usage命令的代理问题

config-template.py, main.py, override-all.json, pkg/openai/dprompt.py, pkg/openai/session.py, pkg/qqbot/cmds/session.py
=> [Feat] 完善情景预设相关内容

pkg/qqbot/cmds/system/cconfig.py, res/wiki/功能使用.md
rt
可能导致或已知的问题: 
现在修改字符串类型的配置项时，需要使用英文双引号（或英文单引号）包括其值
=> [Feat] 支持使用!cfg指令修改子配置项

pkg/utils/updater.py
=> [Feat] 更新时忽略主版本号不同的版本

README.md, pkg/openai/modelmgr.py
实现/解决/优化的内容: 
one-api是一个api整合项目，通过这个项目的反代理，可以像使用gpt系列的/v1/completion接口一样调用国内的大模型，仅仅需要更改一下模型名字。
项目地址：https://github.com/songquanpeng/one-api
因而，仅仅在chatcompletion这个类中加入one-api项目支持的国内模型即可以调用国内大模型。
目前接入的one-api渠道的模型有：讯飞星火大模型(因为不支持stream模式目前无法使用，one-api渠道即将更新，所以先接入了)、智谱ChatGLM、阿里通义千问、百度文心千帆
希望作者大大能在readme中说明下要接入one-api才能用这些模型，同时，我还向switcher插件提交了相应的pull，需要一并整合介绍。
可能导致或已知的问题: 无
=> 加入one-api项目支持的国内大模型

config-template.py, main.py, override-all.json, pkg/openai/api/chat_completion.py, pkg/openai/api/completion.py, pkg/openai/api/model.py, pkg/openai/manager.py, pkg/openai/modelmgr.py, pkg/openai/session.py, pkg/qqbot/message.py, requirements.txt, tests/proxy_test/forward_proxy_test.py
=> Feat: 适配openai>=1.0.0

.github/workflows/update-cmdpriv-template.yml, .github/workflows/update-override-all.yml, pkg/plugin/host.py, pkg/plugin/metadata.py, pkg/qqbot/cmds/plugin/plugin.py, pkg/qqbot/sources/nakuru.py, tests/repo_regexp_test.py
改为使用 GitHub 直接下载源码的形式安装插件，并将插件源地址保存到 `plugins/metadata.json` 中，在更新插件时使用此文件中存储的插件源地址进行最新版本重新安装。
=> Feat: 通过 GitHub API 进行插件安装和更新

config-template.py, override-all.json, pkg/openai/manager.py, pkg/qqbot/cmds/funcs/draw.py
=> Fix: openai>=1.0时绘图命令不兼容

README.md, config-template.py, pkg/openai/modelmgr.py
通过 One API 接入 Google Gemini 模型，暂时不会原生接入，因为本项目原则上只原生接入 OpenAI 的模型。
暂时不支持 PaLM-2；  
带有内容函数时调用通过 One API 接入的模型，风险未知。
=> Feat: 支持 Google Gemini Pro 模型

pkg/qqbot/cmds/system/cconfig.py
=> Fix: cfg 命令无法使用

pkg/qqbot/cmds/session/resend.py
=> Fix: resend 命令失效

pkg/openai/keymgr.py, pkg/openai/session.py, pkg/plugin/host.py, pkg/qqbot/cmds/plugin/plugin.py, pkg/qqbot/cmds/session/default.py, pkg/qqbot/cmds/session/list.py, pkg/qqbot/ratelimit.py, pkg/utils/log.py
=> Chore: 移除过时的兼容性处理代码

pkg/core/app.py, pkg/core/bootutils/log.py, pkg/platform/adapter.py, pkg/platform/manager.py, pkg/platform/sources/aiocqhttp.py, pkg/platform/sources/nakuru.py, pkg/platform/sources/yirimirai.py, requirements.txt, templates/platform.json
现在兼容onebot的框架都可以接入了
- aiocqhttp 只支持反向ws
- aiocqhttp不支持转发消息，转换成文本消息发送
=> Feat: 适配aiocqhttp

main.py, pkg/core/app.py, pkg/core/boot.py, pkg/core/bootutils/log.py, pkg/core/stage.py, pkg/core/stages/build_app.py, pkg/core/stages/load_config.py, pkg/core/stages/setup_logger.py, pkg/pipeline/controller.py, pkg/pipeline/pool.py
=> Feat: 分阶段启动

main.py, pkg/config/impls/json.py, pkg/config/impls/pymodule.py, pkg/config/manager.py, pkg/config/model.py, pkg/core/bootutils/files.py, pkg/platform/sources/qqbotpy.py, templates/metadata/adapter-qq-botpy.json
使用 QQ 官方 API 作为 Q 群（需要测试资格）机器人时，群 id 和 成员 id 均为 字符串，而内部处理逻辑只支持 int，以前会在运行时维护一个映射表，按照顺位分配 int，重启后即丢失，无法进行访问权限等设置。  
现在使用一个摘要算法，取字符串id最后10位，计算其int值，存入 `data/metadata/adapter-qq-botpy.json` 中，用户可自行修改，重启后仍有效。
=> Feat: qq-botpy 适配器对 member 和 group 的 openid 进行静态缓存

pkg/config/migrations/m005_deepseek_cfg_completion.py, pkg/core/stages/migrate.py, pkg/provider/modelmgr/apis/deepseekchatcmpl.py, pkg/provider/modelmgr/modelmgr.py, templates/metadata/llm-models.json, templates/pipeline.json, templates/provider.json
=> Feat: 支持 deepseek 模型

pkg/platform/sources/aiocqhttp.py
当qqbot 发送图片时msg是base64 ， 源代码中缺失对于base64的处理。导致无法发送图片。
关联的issues
Fixes #778
=> 修复aiocqhttp的图片错误

pkg/core/entities.py, pkg/pipeline/cntfilter/cntfilter.py, pkg/pipeline/process/handlers/chat.py, pkg/pipeline/process/handlers/command.py, pkg/pipeline/wrapper/wrapper.py, pkg/provider/entities.py
现在 query.resp_messages 的元素类型支持 Message 和 mirai.MessageChain 两种类型对象。当插件通过 `PersonCommandSent` 或 `PersonNormalMessageReceived` 传递 mirai.MessageChain 作为 reply 时，pipeline上的 wrapper 阶段将被跳过，并将此消息链直接赋值给 query.resp_message_chain。
这个功能在前一版本重构时被破坏了兼容性，故在此修复。
=> Fix: 修复 query.resp_messages 对插件reply的兼容性

pkg/provider/modelmgr/apis/chatcmpl.py
实现/解决/优化的内容: 确认 `chatcmpl` 方法中的 `content` 为字符串，解决与 `yi-large` 模型的兼容性问题。
修正[issue817](https://github.com/RockChinQ/QChatGPT/issues/817)
可能导致或已知的问题: 暂无已知问题，但需要进一步测试以确保所有场景下的兼容性。
=> fix: ensure content is string in chatcmpl call method

pkg/provider/entities.py
实现/解决/优化的内容: 
fixed pkg\provider\entities.py\get_content_mirai_message_chain中ce.type图片类型不正确的异常
- [√] 已阅读仓库[贡献指引](https://github.com/RockChinQ/QChatGPT/blob/master/CONTRIBUTING.md)
- [√] 已与维护者在issues或其他平台沟通此PR大致内容
- [√] 已编写完善的配置文件字段说明（若有新增）
- [√] 已编写面向用户的新功能说明（若有必要）
- [√] 已测试新功能或更改
- [√] 已处理版本兼容性
- [√] 已处理插件兼容问题
可能导致或已知的问题:
=> fixed pkg\provider\entities.py\get_content_mirai_message_chain中ce.type图片类型不正确的异常

pkg/platform/sources/aiocqhttp.py
实现/解决/优化的内容: 
Fixed aiocqhttp mirai.Voice类型无法正确传递url及base64的异常
- [√] 已阅读仓库[贡献指引](https://github.com/RockChinQ/QChatGPT/blob/master/CONTRIBUTING.md)
- [√] 已与维护者在issues或其他平台沟通此PR大致内容
- [√] 已编写完善的配置文件字段说明（若有新增）
- [√] 已编写面向用户的新功能说明（若有必要）
- [√] 已处理版本兼容性
- [] 已处理插件兼容问题
可能导致或已知的问题:
=> Fixed aiocqhttp mirai.Voice类型无法正确传递url及base64的异常

pkg/provider/modelmgr/apis/anthropicmsgs.py, pkg/provider/modelmgr/apis/chatcmpl.py, pkg/provider/modelmgr/apis/ollamachat.py, pkg/utils/image.py
实现/解决/优化的内容:  从 response header 中获取图片文件格式，而不是写死的 `image/jpeg`。由于一部分接口提供商会对图片格式进行验证，所以不能直接使用 `image/jpeg` 作为所有图片的格式。
=> fix: 发送正确的图片格式而不是默认的 `image/jpeg`

pkg/provider/modelmgr/apis/chatcmpl.py
实现/解决/优化的内容: 
在OpenAI ChatCompletion API 请求器处理中转站返回的message时，因部分中转站返回AI回复message中不含role，导致role=none而报Validation Error，故在_make_msg函数中处理完message后添加对role字段的检查，确保 role 字段存在且不为 None。考虑到中转站应该都用OpenAI ChatCompletion API 请求器，所以暂不检查其他请求器返回的message。
#886 
- [ √] 阅读仓库[贡献指引](https://github.com/RockChinQ/QChatGPT/blob/master/CONTRIBUTING.md)了吗？
- [ √] 与项目所有者沟通过了吗？
=> Fix: Add Role Check to Prevent Validation Error

pkg/platform/sources/qqofficial.py
如 Issues #1025 所描述的，在`pkg/platform/sources/qqofficial.py`中`QQOfficialMessageConverter`类的`target2yiri`方法中，对`message`进行了清除操作，导致后续解析出了空的`Plain`。
```python
@staticmethod
async def target2yiri(message:str,message_id:str,pic_url:str,content_type):
yiri_msg_list = []
yiri_msg_list.append(
platform_message.Source(id=message_id,time=datetime.datetime.now())
)
if pic_url is not None:
base64_url = await image.get_qq_official_image_base64(pic_url=pic_url,content_type=content_type)
yiri_msg_list.append(
platform_message.Image(base64=base64_url)
)
message = ''
yiri_msg_list.append(platform_message.Plain(text=message))
chain = platform_message.MessageChain(yiri_msg_list)
return chain
```
*请在方括号间写`x`以打勾
=> fix: remove fatal clearance to message from QQWebhook

pkg/core/bootutils/deps.py, pkg/core/migrations/m020_wecom_config.py, pkg/core/migrations/m021_lark_config.py, pkg/core/migrations/m024_discord_config.py, pkg/core/migrations/m025_gewechat_config.py, pkg/core/migrations/m026_qqofficial_config.py, pkg/core/migrations/m027_wx_official_account_config.py, pkg/core/migrations/m031_dingtalk_config.py, pkg/platform/manager.py, pkg/platform/sources/telegram.py, requirements.txt, templates/platform.json, templates/schema/platform.json
=> feat: add adapter `telegram`

pkg/core/migrations/m025_gewechat_config.py, pkg/core/migrations/m034_gewechat_file_url_config.py, pkg/core/stages/migrate.py, pkg/platform/sources/gewechat.py, pkg/platform/sources/gewechat.yaml, pkg/utils/constants.py, pkg/utils/image.py, templates/platform.json, templates/schema/platform.json
实现/解决/优化的内容: 
围绕 Gewechat 做了些修改
1. 新增：支持聊天记录的消息；
2. 修改：图片消息改为图片常规尺寸图片放弃原来的缩略图
3. 修复 bug： 无法响应设置过微信id的用户
*请在方括号间写`x`以打勾
- [ x ] 阅读仓库[贡献指引](https://github.com/RockChinQ/LangBot/blob/master/CONTRIBUTING.md)了吗？
- [ x ] 与项目所有者沟通过了吗？
- [ x ] 我确定已自行测试所作的更改，确保功能符合预期。
=> 围绕 Gewechat 修改，1）支持聊天记录的消息； 2）图片消息改为图片常规尺寸图片放弃原来的缩略图

pkg/core/app.py
实现/解决/优化的内容: 
让llm重载可以直接获取本地最新的llm_models.json里面的内容
*请在方括号间写`x`以打勾
=> 让llm重载可以直接获取本地最新的llm_models.json里面的内容

libs/dify_service_api/v1/client.py, pkg/platform/sources/dingtalk.py, pkg/platform/sources/qqofficial.py, pkg/platform/types/events.py, pkg/provider/runners/difysvapi.py
实现/解决/优化的内容: 
给dify workflow传递langbot_msg_create_time参数，gewechat的消息时间，方便dify workflow里通过判断微信消息时间戳来做对应的逻辑。
*请在方括号间写`x`以打勾
- [ x ] 阅读仓库[贡献指引](https://github.com/RockChinQ/LangBot/blob/master/CONTRIBUTING.md)了吗？
- [ - ] 与项目所有者沟通过了吗？
- [ x ] 我确定已自行测试所作的更改，确保功能符合预期。
=> 将微信消息时间戳传递给 dify，便于 dify 通过消息时间戳来做业务逻辑。

README.md, README_EN.md, README_JP.md
实现/解决/优化的内容: 
fix typo in README
<a href="https://docs.langbot.app/insight/intro.htmll">功能介绍</a>
=>
<a href="https://docs.langbot.app/insight/intro.html">功能介绍</a>
*请在方括号间写`x`以打勾
- [ x ] 阅读仓库[贡献指引](https://github.com/RockChinQ/LangBot/blob/master/CONTRIBUTING.md)了吗？
- [ x ] 我确定已自行测试所作的更改，确保功能符合预期。
- [ x ] 文档编写了吗？
=> typo: fix README

pkg/platform/sources/gewechat.py
当机器人群名称改名后群聊单独at机器人时候替换@信息为空。暂时解决#1192
*请在方括号间写`x`以打勾
=> 当机器人群名称改名后群聊单独at机器人时候替换@信息为空

pkg/platform/manager.py, pkg/platform/sources/gewechat.py, pkg/utils/image.py
修复bot自己给别人发消息时没有PushContent字段导致判断错误，并修复bot自己发消息自己回复问题#1140
*请在方括号间写`x`以打勾
=> Fixed bot sending messages to others without PushContent field causing error in judgment, and fixed bot sending messages to reply to themselves

pkg/core/bootutils/deps.py, pkg/plugin/installers/github.py, requirements.txt
实现/解决/优化的内容: 
- 使用 certifi 创建自定义 SSL 上下文，确保 HTTPS 连接验证正确
- 为 aiohttp 请求添加 ssl 参数，防止因缺失根证书导致下载失败
- 修正相关错误提示，插件安装流程更稳固
- 将 `certifi` 写入了 `requirements.txt`
- Create a custom SSL context using certifi for proper HTTPS certificate verification
- Add the ssl parameter to aiohttp requests to prevent download failure due to missing root certificates
- Improve error messages and enhance the overall plugin installation process
*请在方括号间写`x`以打勾
=> fix: Fix SSL certificate verification error during GitHub plugin installation

pkg/platform/sources/gewechat.py, pkg/platform/types/message.py
实现/解决/优化的内容: 
优化了gewechat的adapter
1. 重构了send_message 和 reply_message, 只维护一份post message的代码。
2. 新增了WeChatForwardImage，WeChatForwardFile，WeChatAppMsg。
3. target2yiri的群聊前缀处理放到最前面。
4. Image, File对象新增了xml属性，为什么要这么做，因为Forward时候要用。
5. **引用消息**的处理，标识了各个对象，修复了引用消息的@问题。
6. 消息链的未知消息加上了sender_id的前缀，需要确认是否合理。（可能只有微信群会有）
7. set_callback失败，新增了原因备注。
*请在方括号间写`x`以打勾
=> feat(gewechat): 优化了代码结构+fix群聊艾特逻辑，新增消息类型

pkg/platform/sources/gewechat.py
- 重构target2yiri，由原来的if else调整为了策略分派的逻辑。
- 是否艾特机器人，群引用转@的逻辑合并到_ats_bot函数
- 引用消息原来是plain，现在展开为具体的消息类型。
- 公众号卡片的默认会有一条链接消息（确少卡片缩略图）和一条转发消息（xml)
- 重命名了一些变量。
- 
*请在方括号间写`x`以打勾
=> feat(gewechat): 重构target2yiri代码+引用消息展开

pkg/platform/sources/gewechat.py, pkg/platform/types/message.py
- 新增引用消息转发，为什么要做这个事？
- 引用消息中有诸多要素，不好逐个定义在Quote类中。
- 引用消息在消息链的表现是被拆分为Plain和Quote，而gewechat做reply只能按照component维度。
- 引用消息转发定义为新的类型，WechatForwadxxx类的xml消息，用户不订阅，就不感知。可以供一些高级开发者使用。
- @ 修复
- 被引用消息里面带有@bot时，也会触发，这个是不符合预期的。去掉这个逻辑不影响@使用。
- @xxx 做正则剔除时，应该限制长度。
*请在方括号间写`x`以打勾
=> feat(gewechat): 新增引用消息转发+@在引用中的bug修复

pkg/platform/botmgr.py, pkg/platform/sources/lark.py, pkg/platform/sources/lark.yaml, pkg/provider/runners/difysvapi.py, templates/metadata/pipeline/ai.yaml, web/src/app/home/bots/components/bot-form/BotForm.tsx, web/src/app/infra/entities/api/index.ts
实现/解决/优化的内容: 
feature: #1364  #1302 #1283 
效果图：
1. 使用飞书卡片消息来实现消息的更新(普通消息更新有次数限制)
2. 飞书发消息后，先生成一个卡片消息，内容为"思考中"。
3. 调用dify获得数据后，积累一定消息数(如10条)就更新一次卡片，从而达到实现流式输出的效果。
1. 在飞书开发者后台创建一个卡片(可以使用飞书卡片搭建工具)
2. 机器人设置打开卡片功能，并设置卡片模板ID
3. dify流水线要打开流式输出开关
- 此次也修复了lark config变化后，旧连接不清理，导致连接很多，消息监听有可能随机到其中一个老连接上的问题。
*请在方括号间写`x`以打勾
=> feat:support dify message streaming output

pkg/platform/sources/aiocqhttp.py, pkg/platform/types/message.py
增加了onbotv11适配器的接受和发送表情的功能，新增了face消息类，将超级表情骰子和划拳一同归为face,但是有部分古老表情在消息中拿不到face_name,如需要需要需插件或者后续将表情表适配？
=> feat:add onebotv11 face send and accept but some face no name.

pkg/provider/modelmgr/requesters/ollamachat.py
Fixed the issue where Ollama's embedding model was not functioning properly. (#1601)
Reason: The `invoke_embedding` in `pkg\provider\modelmgr\requesters\ollamachat.py` directly returns the result of `client.embed` instead of the `embeddings` attribute within it, which does not meet the required data type.
=> Fix: Fixed the issue where Ollama's embedding model was not functioning properly

pkg/pipeline/resprule/rules/atbot.py
Fix can't '@' in QQ group.
> Summary of what you implemented/solved/optimized: Fix: Correct data type mismatch in AtBotRule, let "@" can work in QQ group.
=> Fix: Correct data type mismatch in AtBotRule
