langbot-app/LangBot

config-template.py, pkg/openai/manager.py, pkg/openai/modelmgr.py
添加了proxy代理功能，做了以下改动：
1、修改GPT父类以支持proxy功能
2、添加了一个新线程以异步请求proxy回复
3、修改GPT两个子类模型在传入参数处理时的逻辑
4、在config.py添加相关配置
存在的问题：
1、由于新建了线程，可能会产生意想不到的错误
2、GPT父类的入参处理部分处理的不好，还是存在耦合
=> 添加proxy代理功能

config-template.py, pkg/qqbot/blob.py, pkg/qqbot/message.py, pkg/qqbot/process.py, pkg/utils/text2img.py, requirements.txt
=> [Feature] 长消息处理策略

.gitignore, main.py, pkg/utils/updater.py, requirements.txt
替换原有的基于dulwich的根据提交信息进行的更新。  
1. 检查更新改为通过Github API检查是否有新的Release
2. 更新时下载最新的Release，解压覆盖所有文件
3. 完成后使用requirements.txt或内置依赖要求安装依赖
=> [Feature] 使用语义化版本进行更新

config-template.py, pkg/utils/text2img.py
减小程序包大小，避免版权问题，解决更新时无法写入字体文件导致失败的问题
=> [Feat] 不再自带字体文件

config-template.py, main.py, pkg/database/manager.py, pkg/openai/session.py, pkg/qqbot/command.py
=> [Feat] 支持删除会话的指定或全部历史记录 (#239)

main.py, pkg/utils/announcement.py
=> [Feat] 添加公告输出功能

config-template.py, pkg/database/manager.py, pkg/openai/manager.py, pkg/openai/session.py
=> [Perf] Tokens相关处理逻辑优化

pkg/qqbot/blob.py
=> [Perf] 百度云审核的异常处理

config-template.py, main.py
=> [Feat] 支持反向代理

pkg/openai/keymgr.py
=> [Fix] 修复一处类型注解的错误

cmdpriv-template.json, pkg/qqbot/cmds/system/cmd.py, pkg/qqbot/cmds/system/cmds.py, pkg/qqbot/cmds/system/help.py, pkg/qqbot/cmds/system/usage.py
=> [Fix] help_message问题、额度检测接口问题

main.py, pkg/audit/gatherer.py, pkg/openai/manager.py, pkg/openai/session.py, pkg/qqbot/blob.py, pkg/qqbot/cmds/system/help.py, pkg/qqbot/filter.py, pkg/qqbot/ignore.py, pkg/qqbot/manager.py, pkg/qqbot/message.py, pkg/qqbot/process.py, pkg/qqbot/ratelimit.py, pkg/utils/text2img.py, tests/gpt3_test.py
实现/解决/优化的内容: 删除多个冗余的兼容性检查
可能导致或已知的问题:
=> [Chore] 删除冗余的兼容性检查判断

main.py
仅在提供命令行参数`--override`或`-r`时应用`override.json`内的字段进行覆写
可能导致或已知的问题:
=> [Feat] override.json可选应用

tips-custom-template.py
=> 删除tips-custom-template.py中无用字段

main.py, pkg/plugin/host.py, pkg/qqbot/cmds/plugin/plugin.py, pkg/utils/log.py, pkg/utils/pkgmgr.py, requirements.txt
=> [Fix] 循环依赖导致的依赖自动解决失败

config-template.py, override-all.json, pkg/qqbot/ratelimit.py
1. 速度限制支持细化到单个人或群
2. 默认限速策略更改为`drop`
可能导致或已知的问题: 暂无
=> [Feat] 速度限制支持细化到单个人或群

.gitignore, main.py, pkg/utils/announcement.py
=> [Feat] 支持JSON格式的公告

config-template.py, override-all.json, pkg/qqbot/manager.py
=> [Feat] 细化到单个群的响应规则

pkg/qqbot/sources/nakuru.py
=> 修复异常输出时的类型问题

pkg/plugin/host.py, pkg/qqbot/cmds/plugin/plugin.py, res/wiki/插件使用.md
=> [Perf] 优化插件更新相关操作

pkg/qqbot/cmds/aamgr.py, tips-custom-template.py
=> [Perf] 修改指令不存在时的提示信息

pkg/qqbot/manager.py
=> [Fix] 热重载之后不响应群内at

main.py
=> feat: 初始化流程异常处理

pkg/qqbot/manager.py, res/templates/banlist-template.py, res/wiki/功能使用.md
=> [Feat] 支持设置全局群聊/私聊消息禁用

config-template.py, override-all.json, pkg/openai/session.py, pkg/qqbot/message.py, pkg/qqbot/process.py, tips-custom-template.py
=> [Feat] token超限报错时自动重置会话

config-template.py, pkg/openai/modelmgr.py
实现/解决/优化的内容: 
可能导致或已知的问题: `gpt-3.5-turbo-0301` `gpt-4-0314`不再可用
=> Perf more model support

pkg/openai/session.py, pkg/qqbot/cmds/session/reset.py, pkg/qqbot/message.py
=> [Perf] 在session自动重置时保留非default的prompt

pkg/qqbot/cmds/plugin/plugin.py
=> [Fix] plugin启用禁用命令对内容函数不生效

README.md, main.py, pkg/openai/api/chat_completion.py, pkg/openai/modelmgr.py, pkg/openai/session.py, requirements.txt
=> feat: 使用tiktoken计算tokens数

pkg/openai/manager.py
=> [Fix] text的使用量未上报

config-template.py, override-all.json, pkg/qqbot/manager.py
=> [Feat] 支持在群内回复时at发送者

.gitignore, pkg/openai/api/chat_completion.py, pkg/openai/session.py, pkg/plugin/models.py, pkg/qqbot/cmds/session/continue.py, pkg/qqbot/message.py, res/wiki/插件开发.md
=> [Feat] 为NormalMessageResponded事件添加finish_reason参数

pkg/openai/session.py, pkg/plugin/models.py, pkg/qqbot/cmds/session/continue.py, pkg/qqbot/message.py
=> [Feat] NormalMessageResponded添加func_called参数

config-template.py, override-all.json, pkg/openai/api/model.py, pkg/openai/keymgr.py, pkg/qqbot/cmds/funcs/func.py
- 若`config.py`中`switch_strategy='active'`，则每次请求api完成后都会尝试切换到下一个key  
- 当加载了内容函数并且在对话中被调用时，每回合将会产生多个请求，使用此功能可以很好地避免超过免费账号的调用限速
- 现在默认启用此功能
=> [Feat] api-key主动负载均衡

README.md
=> 添加 WikipediaSearch 插件

config-template.py, pkg/openai/modelmgr.py
=> Feat: 更新模型索引

main.py, pkg/openai/manager.py
=> Fix: 反向代理设置无效

README.md
插件列表中添加discountAssistant插件
- [√ ] 已阅读仓库[贡献指引](https://github.com/RockChinQ/QChatGPT/blob/master/CONTRIBUTING.md)
- [√ ] 已与维护者在issues或其他平台沟通此PR大致内容
- [ √] 已编写完善的配置文件字段说明（若有新增）
- [√ ] 已编写面向用户的新功能说明（若有必要）
- [ √] 已测试新功能或更改
- [ ×] 已处理版本兼容性
- [× ] 已处理插件兼容问题
暂无
=> 添加discountAssistant插件

README.md
添加AutoSwitchProxy插件,自动切换clash代理模式以节省流量
可能导致或已知的问题: 
无
=> 添加AutoSwitchProxy插件

.github/workflows/sync-wiki.yml, .github/workflows/test-pr.yml
以 GitHub Workflow 的方式集成 [qcg-tester](https://github.com/RockChinQ/qcg-tester)
=> Test: 集成qcg-tester

.gitignore, pkg/audit/center/apigroup.py, pkg/command/cmdmgr.py, pkg/platform/manager.py, pkg/platform/sources/aiocqhttp.py, pkg/platform/sources/qqbotpy.py, requirements.txt, templates/platform.json
- 支持频道群聊和频道私信
- 支持Q群API（需要资格）
- 由于兼容性问题，群openid会转换成一个seq: int以转换成yirimirai的对象，而重启后又会重新编号。
- 由于兼容性问题，群成员openid也有上述问题。
=> Feat: 接入 QQ 官方 API

pkg/platform/adapter.py, pkg/platform/manager.py, pkg/platform/sources/aiocqhttp.py, pkg/platform/sources/nakuru.py, pkg/platform/sources/qqbotpy.py, pkg/platform/sources/yirimirai.py, templates/platform.json, templates/system.json
=> Feat: 恢复nakuru使用

.github/workflows/build-docker-image.yml, Dockerfile
=> CI: 构建arm64镜像

pkg/platform/sources/aiocqhttp.py
=> Fix: 修复使用llonebot时的协议问题

pkg/pipeline/resprule/rules/atbot.py
=> Fix: 回复并at机器人时会多一个at组件

pkg/platform/sources/aiocqhttp.py
=> Feat: aiocqhttp支持access-token

pkg/platform/sources/aiocqhttp.py, pkg/platform/sources/qqbotpy.py
=> Feat: aiocqhttp 和 qq-botpy 适配器的主动消息发送接口

pkg/config/migrations/m2_openai_config_migration.py, pkg/core/app.py, pkg/core/stages/load_config.py, pkg/core/stages/migrate.py, pkg/provider/modelmgr/apis/chatcmpl.py, pkg/provider/modelmgr/modelmgr.py, pkg/provider/session/sessionmgr.py, templates/metadata/llm-models.json, templates/provider.json
- 现在每次启动会尝试从中央服务器获取最新的模型列表
- 通过模型列表选择每个模型的 token管理器 和 请求器 并构建模型信息对象
- 支持编辑 `data/metadata/llm-models.json` 添加自定义的模型信息
=> Feat: 允许自定义模型信息

pkg/provider/modelmgr/apis/anthropicmsgs.py, pkg/provider/tools/toolmgr.py, templates/metadata/llm-models.json
- 为 Claude 添加视觉支持
- Tool Use 的SDK尚处于Beta阶段，故暂不支持
=> Perf: Claude 的能力完善支持

pkg/config/migrations/m008_ad_fixwin_config_migrate.py, pkg/core/stages/migrate.py, pkg/pipeline/ratelimit/algos/fixedwin.py, templates/pipeline.json
=> Feat: fixwin限速支持设置窗口大小

pkg/config/migrations/m009_msg_truncator_cfg.py, pkg/core/stages/migrate.py, pkg/pipeline/msgtrun/msgtrun.py, pkg/pipeline/msgtrun/truncator.py, pkg/pipeline/msgtrun/truncators/round.py, pkg/pipeline/stagemgr.py, templates/pipeline.json
=> Feat: 消息截断器

pkg/pipeline/resprule/resprule.py, pkg/pipeline/resprule/rules/prefix.py, pkg/provider/modelmgr/apis/chatcmpl.py
=> Release 3.2.3

pkg/core/app.py, pkg/core/boot.py, pkg/core/note.py, pkg/core/notes/n001_classic_msgs.py, pkg/core/notes/n002_selection_mode_on_windows.py, pkg/core/stages/build_app.py, pkg/core/stages/show_notes.py, pkg/utils/announce.py, pkg/utils/version.py
=> Feat: 添加启动信息阶段

pkg/command/cmdmgr.py, pkg/command/operators/ollama.py, pkg/config/migrations/m010_ollama_requester_config.py, pkg/core/stages/migrate.py, pkg/provider/modelmgr/apis/ollamachat.py, pkg/provider/modelmgr/apis/ollamachatcmpl.py, pkg/provider/modelmgr/modelmgr.py, requirements.txt, templates/provider.json
#842 
实现/解决/优化的内容: 
1. 集成Ollama平台API, 与Ollama平台上的模型进行非流式对话;
2. 新增4个Ollama平台的命令;
- [√] 已阅读仓库[贡献指引](https://github.com/RockChinQ/QChatGPT/blob/master/CONTRIBUTING.md)
- [√] 已与维护者在issues或其他平台沟通此PR大致内容
可能导致或已知的问题:
=> Feat: Ollama平台集成

pkg/core/app.py, pkg/core/migrations/m012_runner_config.py, pkg/core/stages/build_app.py, pkg/core/stages/migrate.py, pkg/pipeline/process/handlers/chat.py, pkg/provider/runner.py, pkg/provider/runnermgr.py, pkg/provider/runners/localagent.py, templates/provider.json
现在可以扩展 `pkg.provider.runner.RequestRunner` 以修改请求大模型的流程。
=> Feat: Runner 组件抽象

pkg/pipeline/cntfilter/cntfilter.py
=> fix: 消息忽略规则失效 (#854)

pkg/platform/sources/qqbotpy.py
=> Feat: 添加对 QQ 官方 API 私聊场景的支持

pkg/config/impls/yaml.py, pkg/config/manager.py
=> Feat: 添加yaml配置文件的支持

pkg/platform/sources/aiocqhttp.py
实现/解决/优化的内容: 添加了针对报错内容对event.sender中'role'的存在性检查
=> fix: 添加了针对报错内容对event.sender中'role'的存在性检查

pkg/api/http/controller/group.py, pkg/api/http/controller/groups/system.py, pkg/api/http/controller/groups/user.py, pkg/api/http/controller/main.py, pkg/api/http/service/user.py, pkg/core/app.py, pkg/core/bootutils/deps.py, pkg/core/migrations/m013_http_api_config.py, pkg/core/stages/build_app.py, pkg/core/stages/load_config.py, pkg/persistence/entities/base.py, pkg/persistence/entities/user.py, pkg/persistence/mgr.py, pkg/utils/constants.py, requirements.txt, templates/schema/system.json, templates/system.json, web/src/App.vue, web/src/components/InitDialog.vue, web/src/components/LoginDialog.vue, web/src/plugins/index.js, web/src/store/index.js
=> Feat: 用户鉴权

pkg/provider/modelmgr/requesters/ollamachat.py
- 修复 #939 #945 
- 添加对 Ollama 模型的视觉和函数调用支持
*请在方括号间写`x`以打勾
=> feat: 为 ollama 支持视觉和函数调用

libs/dify_service_api/test.py, libs/dify_service_api/v1/client.py, pkg/core/migrations/m017_dify_api_timeout_params.py, pkg/core/stages/migrate.py, pkg/pipeline/preproc/preproc.py, pkg/pipeline/process/handlers/chat.py, pkg/provider/runners/difysvapi.py, pkg/utils/pkgmgr.py, templates/provider.json
=> perf: 完善 dify api runner

pkg/pipeline/preproc/preproc.py, pkg/platform/sources/aiocqhttp.py, pkg/provider/entities.py, pkg/provider/modelmgr/requester.py, pkg/provider/modelmgr/requesters/anthropicmsgs.py, pkg/provider/modelmgr/requesters/chatcmpl.py, pkg/provider/modelmgr/requesters/ollamachat.py, pkg/provider/runners/difysvapi.py, pkg/provider/runners/localagent.py, pkg/utils/image.py
=> fix: 下载 QQ 图片时的400问题

pkg/core/migrations/m019_zhipuai_config.py, pkg/core/stages/migrate.py, pkg/provider/modelmgr/modelmgr.py, pkg/provider/modelmgr/requesters/xaichatcmpl.py, pkg/provider/modelmgr/requesters/zhipuaichatcmpl.py, templates/metadata/llm-models.json, templates/provider.json, templates/schema/provider.json
=> feat: add supports for zhipuai(chatglm)

pkg/plugin/context.py, pkg/provider/runners/difysvapi.py
- 支持显示 dify agent 生成的图片文件
*请在方括号间写`x`以打勾
=> fix(dify): display agent image

libs/wecom_api/api.py
=> fix：修复了企业微信的accesstoken问题

pkg/core/migrations/m022_lmstudio_config.py, pkg/core/stages/migrate.py, pkg/provider/modelmgr/modelmgr.py, pkg/provider/modelmgr/requesters/lmstudiochatcmpl.py, templates/provider.json, templates/schema/provider.json
=> feat: add supports for LM Studio

README.md, pkg/core/migrations/m023_siliconflow_config.py, pkg/core/stages/migrate.py, pkg/provider/modelmgr/modelmgr.py, pkg/provider/modelmgr/requesters/siliconflowchatcmpl.py, templates/provider.json, templates/schema/provider.json
=> feat: siliconflow provider

pkg/core/bootutils/deps.py, pkg/core/migrations/m024_discord_config.py, pkg/core/stages/migrate.py, pkg/platform/manager.py, pkg/platform/sources/discord.py, pkg/platform/types/events.py, requirements.txt, templates/platform.json, templates/schema/platform.json
=> feat: add `discord` adapter

web/src/components/MarketPluginCard.vue, web/src/components/Marketplace.vue, web/src/pages/Plugins.vue, web/src/store/index.js
=> feat: add marketplace

README.md, pkg/core/bootutils/deps.py, pkg/core/migrations/m025_gewechat_config.py, pkg/core/stages/migrate.py, pkg/platform/manager.py, pkg/platform/sources/gewechat.py, requirements.txt, templates/platform.json, templates/schema/platform.json
=> feat: add `gewechat` adapter

libs/official_account_api/api.py, libs/official_account_api/oaevent.py, libs/wecom_api/api.py, pkg/core/migrations/m027_wx_official_account_config.py, pkg/core/stages/migrate.py, pkg/platform/manager.py, pkg/platform/sources/officialaccount.py, pkg/platform/sources/qqofficial.py, pkg/platform/sources/wecom.py, pkg/platform/types/entities.py, templates/platform.json, templates/schema/platform.json
实现/解决/优化的内容: 
- 添加对微信公众号的支持
- 修复企业微信用户名传递的bug
*请在方括号间写`x`以打勾
=> feat: add support for wechat official account 

pkg/core/migrations/m021_lark_config.py, pkg/core/migrations/m030_lark_config_cmpl.py, pkg/core/stages/migrate.py, pkg/platform/sources/lark.py, templates/platform.json, templates/schema/platform.json
实现/解决/优化的内容: 
lark http event事件回复消息
*请在方括号间写`x`以打勾
- [x ] 阅读仓库[贡献指引](https://github.com/RockChinQ/LangBot/blob/master/CONTRIBUTING.md)了吗？
- [x ] 与项目所有者沟通过了吗？
- [x ] 我确定已自行测试所作的更改，确保功能符合预期。
- [ x] 相关 issues 链接了吗？
- [ x] 配置项写好了吗？迁移写好了吗？生效了吗？
- [ x] 依赖写到 requirements.txt 和 core/bootutils/deps.py 了吗
- [ x] 文档编写了吗？
=> feat(lark):enable lark callback

libs/dingtalk_api/EchoHandler.py, libs/dingtalk_api/api.py, libs/dingtalk_api/dingtalkevent.py, libs/wecom_api/api.py, pkg/core/bootutils/deps.py, pkg/core/migrations/m031_dingtalk_config.py, pkg/core/stages/migrate.py, pkg/platform/manager.py, pkg/platform/sources/dingtalk.py, requirements.txt, templates/platform.json, templates/schema/platform.json
实现/解决/优化的内容: 
- 添加对钉钉的支持
*请在方括号间写`x`以打勾
=> feat: add support for dingtalk

pkg/platform/sources/gewechat.py
添加gewe微信接口中voice语音的处理
实现/解决/优化的内容: 
*请在方括号间写`x`以打勾
=> Update gewechat.py 添加gewe微信接口中voice语音的处理

pkg/platform/sources/gewechat.py
粗略解决gewe中消息平台主动发送消息给gewe,对gewechat模块中send message进行了修改
*请在方括号间写`x`以打勾
=> '个人微信中主动发送信息send_message的修改'

pkg/platform/sources/gewechat.py
个人微信中主动发送图片的修改，但是只能发送链接
*请在方括号间写`x`以打勾
- [x ] 阅读仓库[贡献指引](https://github.com/RockChinQ/LangBot/blob/master/CONTRIBUTING.md)了吗？
- [x ] 与项目所有者沟通过了吗？
- [x ] 我确定已自行测试所作的更改，确保功能符合预期。
=> 个人微信中主动发送图片的修改，但是只能发送链接

pkg/provider/modelmgr/entities.py, pkg/provider/modelmgr/requesters/anthropicmsgs.py
实现/解决/优化的内容: 针对Anthropic Claude-3-7-Sonnet新的thinking功能添加参数与开关
*请在方括号间写`x`以打勾
=> 添加针对Anthropic新模型的thinking开关

libs/dingtalk_api/EchoHandler.py, libs/dingtalk_api/api.py, libs/dingtalk_api/dingtalkevent.py, pkg/platform/sources/dingtalk.py
=> feat(dingtalk): add supports for audio receiving

pkg/platform/sources/gewechat.py
解决了gewe更新回调参数data和typename字段改变造成的不回复的问题
*请在方括号间写`x`以打勾
=> '修复了gewe更新回调参数data和typename字段改变造成的不回复的问题'

pkg/platform/sources/qqofficial.py, pkg/platform/sources/wecom.py
=> fix: wrong group id in qqofficial web hook

pkg/core/entities.py, pkg/pipeline/preproc/preproc.py, pkg/provider/runners/dashscopeapi.py, pkg/provider/runners/difysvapi.py
- 为 query 添加 变量列表
*请在方括号间写`x`以打勾
=> feat: add query variables

libs/official_account_api/api.py, pkg/core/migrations/m035_wxoa_mode.py, pkg/core/stages/migrate.py, pkg/platform/sources/officialaccount.py, templates/platform.json, templates/schema/platform.json
实现/解决/优化的内容: 
微信公众号对于回复有严格限制（15s之内），通过此方法可以使用另外一种方式获取15s之外的回复。
*请在方括号间写`x`以打勾
=> feat: add support for longer response in wxoa

libs/official_account_api/api.py, pkg/platform/sources/officialaccount.py
实现/解决/优化的内容: 
加强微信公众号的逻辑性，防止无意义的字符串干扰ai回答。
*请在方括号间写`x`以打勾
=> fix: eliminate critical message queue blockage in wxoa

pkg/platform/sources/gewechat.py
=> '增加了主动发送at信息'

pkg/platform/sources/gewechat.py
增加引用消息回复（暂时只是引用是机器人消息时候构建at并传入消息），增加小程序，转账，红包，视频号等消息的判断。简单解决#1200
*请在方括号间写`x`以打勾
=> 增加引用消息回复（暂时只是引用是机器人消息时候构建at并传入消息），增加小程序，转账，红包，视频号等消息的判断。

libs/official_account_api/api.py, pkg/core/migrations/m036_wxoa_loading_message.py, pkg/core/stages/migrate.py, pkg/platform/sources/officialaccount.py, templates/platform.json, templates/schema/platform.json
实现/解决/优化的内容: 
添加对公众号中加载信息的修改支持
*请在方括号间写`x`以打勾
=> feat: add support for loading message in wxoa

pkg/command/operators/func.py, pkg/provider/session/sessionmgr.py, pkg/provider/tools/loader.py, pkg/provider/tools/loaders/plugin.py, pkg/provider/tools/toolmgr.py
=> feat: tool loader abstraction

pkg/platform/sources/gewechat.py
处理at全员的atall,以及修复回复公众号和微信团队的问题,修复#1140
*请在方括号间写`x`以打勾
=> 处理at全员的atall,以及修复回复公众号和微信团队的问题

README.md, README_EN.md, README_JP.md
=> doc(README): add mcp comments

pkg/utils/constants.py
=> chore: bump version 3.4.11

README.md, README_EN.md, README_JP.md
=> doc(README): add planning platforms comments

README.md, README_EN.md, README_JP.md
=> doc(README): contributors

libs/official_account_api/api.py, pkg/platform/sources/officialaccount.py
实现/解决/优化的内容: 
规范语法
*请在方括号间写`x`以打勾
=> fix: format the code 

pkg/platform/sources/aiocqhttp.py
=> perf: use source_platform_object to pass source event in aiocqhttp

README.md, README_EN.md, README_JP.md
=> doc(README): add 3.13 in python version badge

templates/metadata/pipeline/ai.yaml, templates/metadata/pipeline/output.yaml, templates/metadata/pipeline/safety.yaml, templates/metadata/pipeline/trigger.yaml
=> chore: add pipeline config metadata

pkg/api/http/service/bot.py, pkg/api/http/service/model.py, pkg/platform/manager.py
=> feat: binding bots with runtime

pkg/api/http/controller/main.py
=> fix: static_file sent with wrong mimetype

pkg/utils/constants.py
=> chore: release v3.4.11.1

pkg/provider/runners/difysvapi.py
=> feat(dify): throw error event

pkg/platform/manager.py, pkg/platform/sources/gewechat.py
=> fix(gewe): should not block main launching process (#1163)

pkg/platform/sources/gewechat.py, pkg/platform/sources/lark.py
=> perf: add debugging msg for webhook style adapters

pkg/provider/modelmgr/requesters/chatcmpl.py, pkg/provider/modelmgr/requesters/deepseekchatcmpl.py, pkg/provider/modelmgr/requesters/giteeaichatcmpl.py, pkg/provider/modelmgr/requesters/moonshotchatcmpl.py
=> perf(chatcmpl): use `extra_body` to pass args

pkg/provider/modelmgr/requesters/anthropicmsgs.py
=> perf(claude): ensure system message removed (#867)

pkg/provider/modelmgr/requesters/anthropicmsgs.py, pkg/provider/modelmgr/requesters/chatcmpl.py
=> perf(chatcmpl): remove `space` from `base-url`

pkg/utils/constants.py
=> chore: release v3.4.11.2

docker-compose.yaml
=> chore: provides `TZ=Asia/Shanghai` in docker-compose.yaml as default

libs/dingtalk_api/api.py, pkg/core/migrations/m038_tg_dingtalk_markdown.py, pkg/core/stages/migrate.py, pkg/platform/sources/dingtalk.py, pkg/platform/sources/telegram.py, templates/platform.json, templates/schema/platform.json
实现/解决/优化的内容: 
添加对钉钉和telegram的markdown卡片支持
*请在方括号间写`x`以打勾
=> add support for markdown card in dingtalk & tg

templates/schema/platform.json
=> chore: add slack config schema

templates/provider.json, templates/schema/provider.json
=> chore: provide default prompt

pkg/utils/constants.py
=> chore: release v3.4.12

pkg/core/bootutils/deps.py, pkg/platform/sources/slack.yaml, pkg/platform/sources/telegram.py, requirements.txt
实现/解决/优化的内容: 
修复telegram的markdown转译问题
*请在方括号间写`x`以打勾
=> fix: markdown and image problems in tg

pkg/utils/constants.py
=> chore: release v3.4.12.1

templates/platform.json
=> fix: slack is incorrectly enabled as default

pkg/utils/constants.py
=> chore: release v3.4.13

.github/ISSUE_TEMPLATE/bug-report.yml
=> chore: perf issue template

pkg/core/app.py, pkg/core/stages/load_config.py, pkg/platform/sources/qqbotpy.py, templates/metadata/adapter-qq-botpy.json
=> refactor: remove adapter-qq-botpy.json metadata

pkg/provider/modelmgr/requesters/bailianchatcmpl.py, requirements.txt
=> fix: bailian api streaming mode can't be established

pkg/platform/sources/telegram.py
实现/解决/优化的内容: 
- fix: #1202 
- fix: telegram的markdown模式在没有开启时，不会处理llm产生的消息
*请在方括号间写`x`以打勾
=> Telegram supergroup fix

pkg/platform/sources/lark.py
实现/解决/优化的内容: 
删除飞书中的print函数
*请在方括号间写`x`以打勾
=> fix: delete print function in lark

pkg/provider/modelmgr/requesters/chatcmpl.py
实现/解决/优化的内容: 
fix: #990 
*请在方括号间写`x`以打勾
=> fix: add reasoning content for deepseek-reasoner

pkg/provider/modelmgr/requesters/moonshotchatcmpl.py
=> fix(moonshot): tool_call_id not found error (#1040)

libs/wecom_customer_service_api/api.py, libs/wecom_customer_service_api/wecomcsevent.py, pkg/platform/sources/wecomcs.py, pkg/platform/sources/wecomcs.yaml, templates/platform.json
实现/解决/优化的内容: 
- 添加对企业微信客服的支持
- fix: #1132 
*请在方括号间写`x`以打勾
=> feat: add support for wecom customer service

README.md, README_EN.md, README_JP.md
=> doc: update README

pkg/utils/constants.py
=> chore: release 3.4.14.1

pkg/provider/modelmgr/requesters/chatcmpl.py
=> perf: reduce newline in think tag converting

pkg/core/app.py, pkg/core/notes/n003_print_version.py, pkg/provider/tools/loaders/mcp.py, templates/config.yaml
=> feat: read mcp servers from config.yaml

.gitignore, pkg/provider/runners/difysvapi.py
- fix: #982
- fix: #1312
*请在方括号间写`x`以打勾
=> fix(dify runner): response message event incorrect when using agent app

pkg/utils/constants.py
=> chore: release v3.4.14.2

pkg/platform/sources/gewechat.py, pkg/platform/types/message.py
优化了处理语音消息和群聊图片消息，
增加了发送语音消息（只能发送silk格式语音文件链接）和转发链接消息
*请在方括号间写`x`以打勾
=> 优化了处理语音消息和群聊图片消息，增加了发送语音消息（只能发送silk格式语音文件链接）和转发链接消息

web_ui/.gitignore, web_ui/.husky/pre-commit, web_ui/.lintstagedrc.json, web_ui/.prettierrc.mjs, web_ui/package.json, web_ui/src/app/home/bots/components/bot-form/BotForm.tsx, web_ui/src/app/home/bots/page.tsx, web_ui/src/app/infra/http/HttpClient.ts
实现/解决/优化的内容: 
通知、加载遮罩，需要进一步patch
*请在方括号间写`x`以打勾
=> feat: notification and spinning display step 1

pkg/platform/sources/lark.py
实现/解决/优化的内容: 
- 飞书使用AIDrawing插件无法发送图片
- fix: #1333 
*请在方括号间写`x`以打勾
=> fix: image couldn't be sent in lark

libs/wecom_customer_service_api/api.py
实现/解决/优化的内容: 
fix: #1349 
fix: #1334 
*请在方括号间写`x`以打勾
=> fix: access_token problems in wecomcs

web/src/app/home/bots/botConfig.module.css, web/src/app/home/bots/page.tsx, web/src/app/home/components/home-sidebar/HomeSidebar.tsx, web/src/app/home/layout.module.css, web/src/app/home/layout.tsx, web/src/app/home/plugins/page.tsx, web/src/app/home/plugins/plugin-installed/PluginInstalledComponent.tsx, web/src/app/home/plugins/plugin-installed/plugin-card/PluginCardComponent.tsx, web/src/app/home/plugins/plugin-installed/plugin-card/pluginCard.module.css, web/src/app/home/plugins/plugin-market/PluginMarketComponent.tsx, web/src/app/home/plugins/plugin-market/plugin-market-card/PluginMarketCardComponent.tsx, web/src/app/home/plugins/plugin-market/plugin-market-card/PluginMarketCardVO.ts, web/src/app/home/plugins/plugin-market/plugin-market-card/pluginMarketCard.module.css, web/src/app/home/plugins/plugins.module.css, web/src/app/infra/basic-component/create-card-component/CreateCardComponent.tsx, web/src/app/infra/http/HttpClient.ts, web/src/app/not-found.tsx
实现/解决/优化的内容: 
- 改进了 BotConfigPage、HomeSidebar 和 Plugin 组件的格式和一致性。
- 移除了不必要的 Spin 组件，以防止 BotConfigPage 中的布局塌陷。
- 增强了 HomeSidebar 中的侧边栏选择逻辑，以反映当前的 URL 路径。
- 更新了布局样式，以获得更好的响应性和视觉吸引力。
- 在 PluginMarketComponent 中实现了模拟数据获取，以改进测试和开发。
- 在 PluginMarketComponent 中添加了分页和搜索功能。
- 重构了 PluginInstalledComponent，以简化插件列表的渲染和模态框处理。
- 调整了各种组件中的 CSS 样式，以实现更好的对齐和间距。
- 增强了 NotFound 组件的布局，以获得更好的用户体验。
*请在方括号间写`x`以打勾
=> feat：重构并改进应用的用户界面组件

pkg/utils/constants.py
=> chore: release v3.4.14.3

.github/workflows/build-release-artifacts.yaml
=> ci: fix bad frontend build output path

README.md, README_EN.md, README_JP.md
=> doc: fix deadlinks of doc in README

pkg/core/entities.py, pkg/pipeline/preproc/preproc.py, pkg/provider/modelmgr/modelmgr.py, pkg/provider/session/sessionmgr.py
=> fix: llm model wrongly required when runner is not `local-agent`

pkg/provider/modelmgr/requesters/deepseekchatcmpl.py, pkg/provider/modelmgr/requesters/giteeaichatcmpl.py, pkg/provider/modelmgr/requesters/modelscopechatcmpl.py, pkg/provider/modelmgr/requesters/modelscopechatcmpl.yaml, pkg/provider/modelmgr/requesters/moonshotchatcmpl.py, pkg/provider/modelmgr/requesters/ppiochatcmpl.py, pkg/provider/modelmgr/requesters/ppiochatcmpl.yaml, web/src/app/infra/http/HttpClient.ts
=> fix: bugs in requesters

web/src/app/home/components/dynamic-form/DynamicFormItemComponent.tsx
=> perf: no delay for model selector hover card

pkg/utils/importutil.py
=> fix: windows path bug in importutil

pkg/utils/constants.py
=> chore: release v4.0.1

.github/pull_request_template.md, Dockerfile
=> ci: update Dockerfile

pkg/platform/sources/lark.py
实现/解决/优化的内容: 
fix: #1425 
*请在方括号间写`x`以打勾
=> fix:lark adapter listeners init problem

web/src/app/home/models/component/llm-card/LLMCard.module.css
实现/解决/优化的内容: #1450 
*请在方括号间写`x`以打勾
=> 解决webUI模型配置页面卡片溢出问题

pkg/pipeline/longtext/strategies/image.py
=> fix: lru bug in t2i (#1445)

libs/dingtalk_api/api.py
=> fix: dingtalk adapter couldn't handle images

pkg/platform/sources/wechatpad.py, pkg/platform/types/message.py
…nd transmitted in base64 format.
增加了WeChatFile消息类，以及增加适配器处理文件消息并以base64传输。
=> feat:add new messagetyps WeChatFile and add wechat file is accepted and transmitted in base64 format.

pkg/platform/sources/aiocqhttp.py, pkg/platform/types/message.py
…n local.
File消息类增加了url,以及给适配器（napcat）添加了接受文件和发送文件的功能
=> feat:add file url and add onebotv11(napcat) send file and seve file in local.

pkg/pipeline/cntfilter/cntfilter.py
-In the ContentFilterStage, logic for handling empty messages has been added to ensure that the pipeline continues to process even when the message is empty.
- This change enhances the robustness of content filtering, preventing potential issues caused by empty messages.
- This optimization was implemented to address the issue where, when someone is @ in a group chat and a message is sent without any content, the Source type messages in the message chain are lost.
=> refactor(ContentFilterStage): Add logic for handling empty messages

pkg/platform/sources/wechatpad.py
聊天的@内容需要保留，这样有的插件（比如reminder）可以使用@用户id信息做相关业务处理。
converters的日志没有输出，一并修复了。
Ben
=> 聊天的@用户id内容需要保留

pkg/platform/sources/wechatpad.py
=> fix(wechatpad): @所有人的情况下，修复@机器人消息未被正确解析的问题

pkg/persistence/migrations/dbm001_migrate_v3_config.py, pkg/pipeline/bansess/bansess.py, pkg/pipeline/process/handlers/chat.py, pkg/pipeline/process/process.py, pkg/utils/announce.py, pkg/utils/version.py, templates/config.yaml, templates/metadata/pipeline/trigger.yaml
- 增加命令功能是否启用配置，针对不同使用要求灵活配置系统自带命令启用功能
- 增加版本请求、公告请求超时(api.github.com某些情况无法访问)引起的结果返回异常问题
- 修正AI连接异常情况下，会先推送流式卡片而不更新输出的问题
=> add cmd enable config & fix announce request timeout & fix send card with disconnect ai platform

libs/wecom_api/api.py, pkg/platform/sources/officialaccount.py, pkg/platform/sources/wecom.py
=> fix: wecom function

pkg/pipeline/longtext/longtext.py, pkg/pipeline/longtext/strategies/forward.py, templates/default-pipeline-config.json, templates/metadata/pipeline/output.yaml
=> perf: disable long message processing as default

README.md, pkg/provider/runners/tboxapi.py, pyproject.toml, templates/metadata/pipeline/ai.yaml
feature: supported Tbox runner #1663
=> feat: supported Tbox runner
